### PR TITLE
feat: add tweet list section

### PR DESCRIPTION
**Pull request by zlatanpham**

### CODE REVIEW

**Comment by thuutri** [comment]
I cannot request you to review this PR. If you get this notice, please review this PR. @zlatanpham

**Review by zlatanpham — COMMENTED** [review]
@thuutri I noticed it seems hanging for ever in the first load on Chrome (ideally open an incognito tab to test it). Can you get it testing?

image

**Comment by thuutri** [comment]
I think I completed it. @zlatanpham  Please review again.

**Comment by zlatanpham** [comment]
@thuutri this is looking good. Just need to wait for others to confirm the design.

**Pull request merged**
